name: Android Emulator Workflow

on:
  push:
    branches: [ "feature/emulator" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'android'
          java-version: '17'
          components: 'platform-tools, emulator'

      - name: Install Android SDK components
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;default;x86_64"
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"

      - name: Start emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd testRunnner \
            -skin 1080x1920 \
            -no-snapshot \
            -no-audio \
            -no-boot-anim \
            -accel auto \
            -gpu auto \
            -qemu -lcd-density 420 > /dev/null 2>&1 &

      - name: Wait for emulator to be ready
        run: adb wait-for-device

      - name: List devices
        run: adb devices
