name: run

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x ./.github/scripts/InstallChrome.sh
          ./.github/scripts/startEmulator.sh 

      - name: Test
        run: mvn clean install