name: run

on:
  push:
    branches: [ "feature/emulator" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start Emulator #
        run: |
          chmod +x ./.github/scripts/InstallChrome.sh
          ./.github/scripts/startEmulator.sh 

#      - name: Test
#        run: mvn clean install